//
//  SampleStyleKit.m
//  BFWDrawView
//
//  Created by Tom Brodhurst-Hill on 2/02/2015.
//  Copyright (c) 2015 BareFeetWare. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "SampleStyleKit.h"


@implementation SampleStyleKit

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawPacManWithFrame: (CGRect)frame
{
    //// Color Declarations
    UIColor* pacManColor = [UIColor colorWithRed: 1 green: 0.806 blue: 0 alpha: 1];

    //// Oval Drawing
    CGRect ovalRect = CGRectMake(CGRectGetMinX(frame), CGRectGetMinY(frame), CGRectGetWidth(frame), CGRectGetHeight(frame));
    UIBezierPath* ovalPath = UIBezierPath.bezierPath;
    [ovalPath addArcWithCenter: CGPointMake(CGRectGetMidX(ovalRect), CGRectGetMidY(ovalRect)) radius: CGRectGetWidth(ovalRect) / 2 startAngle: 24 * M_PI/180 endAngle: -24 * M_PI/180 clockwise: YES];
    [ovalPath addLineToPoint: CGPointMake(CGRectGetMidX(ovalRect), CGRectGetMidY(ovalRect))];
    [ovalPath closePath];

    [pacManColor setFill];
    [ovalPath fill];
}

+ (void)drawBathroomWithFrame: (CGRect)frame
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* translucentBlack = [UIColor colorWithRed: 0 green: 0 blue: 0 alpha: 0.5];
    UIColor* baseColor = [UIColor colorWithRed: 0.808 green: 0.638 blue: 0.425 alpha: 1];
    CGFloat baseColorRGBA[4];
    [baseColor getRed: &baseColorRGBA[0] green: &baseColorRGBA[1] blue: &baseColorRGBA[2] alpha: &baseColorRGBA[3]];

    UIColor* baseLightColor = [UIColor colorWithRed: (baseColorRGBA[0] * 0.5 + 0.5) green: (baseColorRGBA[1] * 0.5 + 0.5) blue: (baseColorRGBA[2] * 0.5 + 0.5) alpha: (baseColorRGBA[3] * 0.5 + 0.5)];

    //// Shadow Declarations
    UIColor* bottomThinShadow = translucentBlack;
    CGSize bottomThinShadowOffset = CGSizeMake(0.1, 1.1);
    CGFloat bottomThinShadowBlurRadius = 2;
    UIColor* bottomShadow = translucentBlack;
    CGSize bottomShadowOffset = CGSizeMake(0.1, 2.1);
    CGFloat bottomShadowBlurRadius = 3;
    UIColor* highlightShadow = baseLightColor;
    CGSize highlightShadowOffset = CGSizeMake(0.1, -2.1);
    CGFloat highlightShadowBlurRadius = 5;


    //// Subframes
    CGRect bathroomGroup = CGRectMake(CGRectGetMinX(frame), CGRectGetMinY(frame), CGRectGetWidth(frame), CGRectGetHeight(frame));


    //// Bathroom Group
    {
        //// Bath Roof and Wall Group
        {
            CGContextSaveGState(context);
            CGContextSetAlpha(context, 0.12);
            CGContextBeginTransparencyLayer(context, NULL);


            //// Bath Wall Group
            {
                //// Rectangle Drawing
                UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.00000 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.24138 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.01613 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.00000 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.93103 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.24138 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectanglePath fill];


                //// Rectangle 49 Drawing
                UIBezierPath* rectangle49Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.19355 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.24138 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.20968 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.19355 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.93103 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.24138 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle49Path fill];


                //// Rectangle 50 Drawing
                UIBezierPath* rectangle50Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.38710 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.24138 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.40323 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.38710 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.93103 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.24138 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle50Path fill];


                //// Rectangle 51 Drawing
                UIBezierPath* rectangle51Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.58065 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.24138 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.59677 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.58065 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.93103 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.24138 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle51Path fill];


                //// Rectangle 52 Drawing
                UIBezierPath* rectangle52Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.77419 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.24138 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.79032 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.77419 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.93103 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.24138 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle52Path fill];


                //// Rectangle 53 Drawing
                UIBezierPath* rectangle53Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.96774 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.24138 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.98387 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.96774 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.93103 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.24138 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle53Path fill];


                //// Rectangle 54 Drawing
                UIBezierPath* rectangle54Path = UIBezierPath.bezierPath;
                [rectangle54Path moveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.19692 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.68731 * CGRectGetHeight(bathroomGroup))];
                [rectangle54Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.20834 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.66296 * CGRectGetHeight(bathroomGroup))];
                [rectangle54Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.01275 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.24372 * CGRectGetHeight(bathroomGroup))];
                [rectangle54Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.00134 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.26808 * CGRectGetHeight(bathroomGroup))];
                [rectangle54Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.19692 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.68731 * CGRectGetHeight(bathroomGroup))];
                [rectangle54Path closePath];
                [UIColor.whiteColor setFill];
                [rectangle54Path fill];


                //// Rectangle 55 Drawing
                UIBezierPath* rectangle55Path = UIBezierPath.bezierPath;
                [rectangle55Path moveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.01275 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.68731 * CGRectGetHeight(bathroomGroup))];
                [rectangle55Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.00134 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.66296 * CGRectGetHeight(bathroomGroup))];
                [rectangle55Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.19692 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.24372 * CGRectGetHeight(bathroomGroup))];
                [rectangle55Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.20834 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.26808 * CGRectGetHeight(bathroomGroup))];
                [rectangle55Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.01275 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.68731 * CGRectGetHeight(bathroomGroup))];
                [rectangle55Path closePath];
                [UIColor.whiteColor setFill];
                [rectangle55Path fill];


                //// Rectangle 56 Drawing
                UIBezierPath* rectangle56Path = UIBezierPath.bezierPath;
                [rectangle56Path moveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.39047 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.68731 * CGRectGetHeight(bathroomGroup))];
                [rectangle56Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.40189 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.66296 * CGRectGetHeight(bathroomGroup))];
                [rectangle56Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.20630 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.24372 * CGRectGetHeight(bathroomGroup))];
                [rectangle56Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.19488 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.26808 * CGRectGetHeight(bathroomGroup))];
                [rectangle56Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.39047 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.68731 * CGRectGetHeight(bathroomGroup))];
                [rectangle56Path closePath];
                [UIColor.whiteColor setFill];
                [rectangle56Path fill];


                //// Rectangle 57 Drawing
                UIBezierPath* rectangle57Path = UIBezierPath.bezierPath;
                [rectangle57Path moveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.20630 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.68731 * CGRectGetHeight(bathroomGroup))];
                [rectangle57Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.19488 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.66296 * CGRectGetHeight(bathroomGroup))];
                [rectangle57Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.39047 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.24372 * CGRectGetHeight(bathroomGroup))];
                [rectangle57Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.40189 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.26808 * CGRectGetHeight(bathroomGroup))];
                [rectangle57Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.20630 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.68731 * CGRectGetHeight(bathroomGroup))];
                [rectangle57Path closePath];
                [UIColor.whiteColor setFill];
                [rectangle57Path fill];


                //// Rectangle 58 Drawing
                UIBezierPath* rectangle58Path = UIBezierPath.bezierPath;
                [rectangle58Path moveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.58402 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.68731 * CGRectGetHeight(bathroomGroup))];
                [rectangle58Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.59544 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.66296 * CGRectGetHeight(bathroomGroup))];
                [rectangle58Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.39985 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.24372 * CGRectGetHeight(bathroomGroup))];
                [rectangle58Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.38843 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.26808 * CGRectGetHeight(bathroomGroup))];
                [rectangle58Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.58402 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.68731 * CGRectGetHeight(bathroomGroup))];
                [rectangle58Path closePath];
                [UIColor.whiteColor setFill];
                [rectangle58Path fill];


                //// Rectangle 59 Drawing
                UIBezierPath* rectangle59Path = UIBezierPath.bezierPath;
                [rectangle59Path moveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.39985 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.68731 * CGRectGetHeight(bathroomGroup))];
                [rectangle59Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.38843 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.66296 * CGRectGetHeight(bathroomGroup))];
                [rectangle59Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.58402 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.24372 * CGRectGetHeight(bathroomGroup))];
                [rectangle59Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.59544 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.26808 * CGRectGetHeight(bathroomGroup))];
                [rectangle59Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.39985 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.68731 * CGRectGetHeight(bathroomGroup))];
                [rectangle59Path closePath];
                [UIColor.whiteColor setFill];
                [rectangle59Path fill];


                //// Rectangle 60 Drawing
                UIBezierPath* rectangle60Path = UIBezierPath.bezierPath;
                [rectangle60Path moveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.77757 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.68731 * CGRectGetHeight(bathroomGroup))];
                [rectangle60Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.78899 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.66296 * CGRectGetHeight(bathroomGroup))];
                [rectangle60Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.59340 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.24372 * CGRectGetHeight(bathroomGroup))];
                [rectangle60Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.58198 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.26808 * CGRectGetHeight(bathroomGroup))];
                [rectangle60Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.77757 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.68731 * CGRectGetHeight(bathroomGroup))];
                [rectangle60Path closePath];
                [UIColor.whiteColor setFill];
                [rectangle60Path fill];


                //// Rectangle 61 Drawing
                UIBezierPath* rectangle61Path = UIBezierPath.bezierPath;
                [rectangle61Path moveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.59340 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.68731 * CGRectGetHeight(bathroomGroup))];
                [rectangle61Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.58198 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.66296 * CGRectGetHeight(bathroomGroup))];
                [rectangle61Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.77757 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.24372 * CGRectGetHeight(bathroomGroup))];
                [rectangle61Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.78899 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.26808 * CGRectGetHeight(bathroomGroup))];
                [rectangle61Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.59340 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.68731 * CGRectGetHeight(bathroomGroup))];
                [rectangle61Path closePath];
                [UIColor.whiteColor setFill];
                [rectangle61Path fill];


                //// Rectangle 62 Drawing
                UIBezierPath* rectangle62Path = UIBezierPath.bezierPath;
                [rectangle62Path moveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.97112 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.68731 * CGRectGetHeight(bathroomGroup))];
                [rectangle62Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.98253 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.66296 * CGRectGetHeight(bathroomGroup))];
                [rectangle62Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.78695 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.24372 * CGRectGetHeight(bathroomGroup))];
                [rectangle62Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.77553 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.26808 * CGRectGetHeight(bathroomGroup))];
                [rectangle62Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.97112 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.68731 * CGRectGetHeight(bathroomGroup))];
                [rectangle62Path closePath];
                [UIColor.whiteColor setFill];
                [rectangle62Path fill];


                //// Rectangle 63 Drawing
                UIBezierPath* rectangle63Path = UIBezierPath.bezierPath;
                [rectangle63Path moveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.78695 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.68731 * CGRectGetHeight(bathroomGroup))];
                [rectangle63Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.77553 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.66296 * CGRectGetHeight(bathroomGroup))];
                [rectangle63Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.97112 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.24372 * CGRectGetHeight(bathroomGroup))];
                [rectangle63Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.98253 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.26808 * CGRectGetHeight(bathroomGroup))];
                [rectangle63Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.78695 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.68731 * CGRectGetHeight(bathroomGroup))];
                [rectangle63Path closePath];
                [UIColor.whiteColor setFill];
                [rectangle63Path fill];
            }


            //// Bath Roof Group
            {
                //// Rectangle 2 Drawing
                UIBezierPath* rectangle2Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.03226 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.06452 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.03226 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle2Path fill];


                //// Rectangle 3 Drawing
                UIBezierPath* rectangle3Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.09677 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.12903 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.09677 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle3Path fill];


                //// Rectangle 4 Drawing
                UIBezierPath* rectangle4Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.16129 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.19355 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.16129 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle4Path fill];


                //// Rectangle 5 Drawing
                UIBezierPath* rectangle5Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.22581 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.25806 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.22581 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle5Path fill];


                //// Rectangle 6 Drawing
                UIBezierPath* rectangle6Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.29032 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.32258 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.29032 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle6Path fill];


                //// Rectangle 7 Drawing
                UIBezierPath* rectangle7Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.35484 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.38710 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.35484 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle7Path fill];


                //// Rectangle 8 Drawing
                UIBezierPath* rectangle8Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.41935 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.45161 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.41935 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle8Path fill];


                //// Rectangle 9 Drawing
                UIBezierPath* rectangle9Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.48387 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.51613 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.48387 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle9Path fill];


                //// Rectangle 10 Drawing
                UIBezierPath* rectangle10Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.54839 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.58065 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.54839 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle10Path fill];


                //// Rectangle 11 Drawing
                UIBezierPath* rectangle11Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.61290 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.64516 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.61290 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle11Path fill];


                //// Rectangle 12 Drawing
                UIBezierPath* rectangle12Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.67742 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.70968 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.67742 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle12Path fill];


                //// Rectangle 13 Drawing
                UIBezierPath* rectangle13Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.74194 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.77419 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.74194 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle13Path fill];


                //// Rectangle 14 Drawing
                UIBezierPath* rectangle14Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.80645 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.83871 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.80645 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle14Path fill];


                //// Rectangle 15 Drawing
                UIBezierPath* rectangle15Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.87097 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.90323 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.87097 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle15Path fill];


                //// Rectangle 16 Drawing
                UIBezierPath* rectangle16Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.93548 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.96774 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.93548 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle16Path fill];


                //// Rectangle 17 Drawing
                UIBezierPath* rectangle17Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.06452 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.09677 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.06452 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.20690 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle17Path fill];


                //// Rectangle 18 Drawing
                UIBezierPath* rectangle18Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.12903 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.16129 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.12903 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.20690 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle18Path fill];


                //// Rectangle 19 Drawing
                UIBezierPath* rectangle19Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.19355 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.22581 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.19355 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.20690 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle19Path fill];


                //// Rectangle 20 Drawing
                UIBezierPath* rectangle20Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.25806 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.29032 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.25806 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.20690 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle20Path fill];


                //// Rectangle 21 Drawing
                UIBezierPath* rectangle21Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.32258 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.35484 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.32258 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.20690 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle21Path fill];


                //// Rectangle 22 Drawing
                UIBezierPath* rectangle22Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.38710 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.41935 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.38710 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.20690 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle22Path fill];


                //// Rectangle 23 Drawing
                UIBezierPath* rectangle23Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.45161 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.48387 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.45161 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.20690 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle23Path fill];


                //// Rectangle 24 Drawing
                UIBezierPath* rectangle24Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.51613 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.54839 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.51613 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.20690 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle24Path fill];


                //// Rectangle 25 Drawing
                UIBezierPath* rectangle25Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.58065 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.61290 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.58065 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.20690 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle25Path fill];


                //// Rectangle 26 Drawing
                UIBezierPath* rectangle26Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.64516 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.67742 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.64516 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.20690 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle26Path fill];


                //// Rectangle 27 Drawing
                UIBezierPath* rectangle27Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.70968 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.74194 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.70968 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.20690 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle27Path fill];


                //// Rectangle 28 Drawing
                UIBezierPath* rectangle28Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.77419 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.80645 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.77419 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.20690 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle28Path fill];


                //// Rectangle 29 Drawing
                UIBezierPath* rectangle29Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.83871 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.87097 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.83871 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.20690 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle29Path fill];


                //// Rectangle 30 Drawing
                UIBezierPath* rectangle30Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.90323 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.93548 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.90323 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.20690 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle30Path fill];


                //// Rectangle 31 Drawing
                UIBezierPath* rectangle31Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.96774 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 1.00000 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.96774 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.20690 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle31Path fill];


                //// Rectangle 32 Drawing
                UIBezierPath* rectangle32Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.06452 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.09677 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.06452 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle32Path fill];


                //// Rectangle 33 Drawing
                UIBezierPath* rectangle33Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.12903 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.16129 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.12903 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle33Path fill];


                //// Rectangle 34 Drawing
                UIBezierPath* rectangle34Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.19355 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.22581 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.19355 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle34Path fill];


                //// Rectangle 35 Drawing
                UIBezierPath* rectangle35Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.25806 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.29032 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.25806 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle35Path fill];


                //// Rectangle 36 Drawing
                UIBezierPath* rectangle36Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.32258 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.35484 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.32258 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle36Path fill];


                //// Rectangle 37 Drawing
                UIBezierPath* rectangle37Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.38710 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.41935 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.38710 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle37Path fill];


                //// Rectangle 38 Drawing
                UIBezierPath* rectangle38Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.45161 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.48387 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.45161 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle38Path fill];


                //// Rectangle 39 Drawing
                UIBezierPath* rectangle39Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.51613 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.54839 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.51613 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle39Path fill];


                //// Rectangle 40 Drawing
                UIBezierPath* rectangle40Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.58065 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.61290 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.58065 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle40Path fill];


                //// Rectangle 41 Drawing
                UIBezierPath* rectangle41Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.64516 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.67742 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.64516 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle41Path fill];


                //// Rectangle 42 Drawing
                UIBezierPath* rectangle42Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.70968 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.74194 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.70968 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle42Path fill];


                //// Rectangle 43 Drawing
                UIBezierPath* rectangle43Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.77419 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.80645 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.77419 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle43Path fill];


                //// Rectangle 44 Drawing
                UIBezierPath* rectangle44Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.83871 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.87097 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.83871 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle44Path fill];


                //// Rectangle 45 Drawing
                UIBezierPath* rectangle45Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.90323 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.93548 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.90323 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle45Path fill];


                //// Rectangle 46 Drawing
                UIBezierPath* rectangle46Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.96774 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 1.00000 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.96774 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle46Path fill];


                //// Rectangle 47 Drawing
                UIBezierPath* rectangle47Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.00000 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.03226 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.00000 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.20690 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.13793 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle47Path fill];


                //// Rectangle 48 Drawing
                UIBezierPath* rectangle48Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.00000 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.03226 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.00000 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.06897 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.00000 + 0.5))];
                [UIColor.whiteColor setFill];
                [rectangle48Path fill];


                //// Bezier Drawing
                UIBezierPath* bezierPath = UIBezierPath.bezierPath;
                [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.98387 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.03448 * CGRectGetHeight(bathroomGroup))];
                [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.01613 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.03448 * CGRectGetHeight(bathroomGroup))];
                [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.01613 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.20690 * CGRectGetHeight(bathroomGroup))];
                [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.98387 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.20690 * CGRectGetHeight(bathroomGroup))];
                [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.98387 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.03448 * CGRectGetHeight(bathroomGroup))];
                [bezierPath closePath];
                [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 1.00000 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.03448 * CGRectGetHeight(bathroomGroup))];
                [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 1.00000 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.20690 * CGRectGetHeight(bathroomGroup))];
                [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 1.00000 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.24138 * CGRectGetHeight(bathroomGroup))];
                [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.00000 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.24138 * CGRectGetHeight(bathroomGroup))];
                [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.00000 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.20690 * CGRectGetHeight(bathroomGroup))];
                [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.00000 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.03448 * CGRectGetHeight(bathroomGroup))];
                [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.00000 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.00000 * CGRectGetHeight(bathroomGroup))];
                [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 1.00000 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.00000 * CGRectGetHeight(bathroomGroup))];
                [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 1.00000 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.03448 * CGRectGetHeight(bathroomGroup))];
                [bezierPath closePath];
                [UIColor.whiteColor setFill];
                [bezierPath fill];
            }


            CGContextEndTransparencyLayer(context);
            CGContextRestoreGState(context);
        }


        //// Bath Group
        {
            //// Bath Tub Drawing
            UIBezierPath* bathTubPath = UIBezierPath.bezierPath;
            [bathTubPath moveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.11290 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.82759 * CGRectGetHeight(bathroomGroup))];
            [bathTubPath addCurveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.16129 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.93103 * CGRectGetHeight(bathroomGroup)) controlPoint1: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.11290 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.88472 * CGRectGetHeight(bathroomGroup)) controlPoint2: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.13457 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.93103 * CGRectGetHeight(bathroomGroup))];
            [bathTubPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.51613 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.93103 * CGRectGetHeight(bathroomGroup))];
            [bathTubPath addCurveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.56452 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.82759 * CGRectGetHeight(bathroomGroup)) controlPoint1: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.54285 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.93103 * CGRectGetHeight(bathroomGroup)) controlPoint2: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.56452 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.88472 * CGRectGetHeight(bathroomGroup))];
            [bathTubPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.59677 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.55172 * CGRectGetHeight(bathroomGroup))];
            [bathTubPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.08065 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.55172 * CGRectGetHeight(bathroomGroup))];
            [bathTubPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.11290 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.82759 * CGRectGetHeight(bathroomGroup))];
            [bathTubPath closePath];
            [UIColor.whiteColor setFill];
            [bathTubPath fill];

            ////// Bath Tub Inner Shadow
            CGContextSaveGState(context);
            UIRectClip(bathTubPath.bounds);
            CGContextSetShadowWithColor(context, CGSizeZero, 0, NULL);

            CGContextSetAlpha(context, CGColorGetAlpha([highlightShadow CGColor]));
            CGContextBeginTransparencyLayer(context, NULL);
            {
                UIColor* opaqueShadow = [highlightShadow colorWithAlphaComponent: 1];
                CGContextSetShadowWithColor(context, highlightShadowOffset, highlightShadowBlurRadius, [opaqueShadow CGColor]);
                CGContextSetBlendMode(context, kCGBlendModeSourceOut);
                CGContextBeginTransparencyLayer(context, NULL);

                [opaqueShadow setFill];
                [bathTubPath fill];

                CGContextEndTransparencyLayer(context);
            }
            CGContextEndTransparencyLayer(context);
            CGContextRestoreGState(context);



            //// Bath Right Leg Drawing
            UIBezierPath* bathRightLegPath = UIBezierPath.bezierPath;
            [bathRightLegPath moveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.48387 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.89655 * CGRectGetHeight(bathroomGroup))];
            [bathRightLegPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.51613 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.89655 * CGRectGetHeight(bathroomGroup))];
            [bathRightLegPath addCurveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.54839 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 1.00000 * CGRectGetHeight(bathroomGroup)) controlPoint1: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.51613 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.89655 * CGRectGetHeight(bathroomGroup)) controlPoint2: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.51977 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.94600 * CGRectGetHeight(bathroomGroup))];
            [bathRightLegPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.51613 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 1.00000 * CGRectGetHeight(bathroomGroup))];
            [bathRightLegPath addCurveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.48387 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.89655 * CGRectGetHeight(bathroomGroup)) controlPoint1: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.49588 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.95385 * CGRectGetHeight(bathroomGroup)) controlPoint2: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.48387 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.89655 * CGRectGetHeight(bathroomGroup))];
            [bathRightLegPath closePath];
            [UIColor.whiteColor setFill];
            [bathRightLegPath fill];


            //// Tap Drawing
            UIBezierPath* tapPath = UIBezierPath.bezierPath;
            [tapPath moveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.12903 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.55172 * CGRectGetHeight(bathroomGroup))];
            [tapPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.12903 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.37931 * CGRectGetHeight(bathroomGroup))];
            [tapPath addCurveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.16935 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.27586 * CGRectGetHeight(bathroomGroup)) controlPoint1: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.12903 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.37931 * CGRectGetHeight(bathroomGroup)) controlPoint2: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.13195 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.27871 * CGRectGetHeight(bathroomGroup))];
            [tapPath addCurveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.20968 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.37931 * CGRectGetHeight(bathroomGroup)) controlPoint1: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.20676 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.27301 * CGRectGetHeight(bathroomGroup)) controlPoint2: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.20968 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.37931 * CGRectGetHeight(bathroomGroup))];
            [tapPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.19355 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.37931 * CGRectGetHeight(bathroomGroup))];
            [tapPath addCurveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.16935 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.31034 * CGRectGetHeight(bathroomGroup)) controlPoint1: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.19355 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.37931 * CGRectGetHeight(bathroomGroup)) controlPoint2: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.19194 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.30982 * CGRectGetHeight(bathroomGroup))];
            [tapPath addCurveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.14516 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.37931 * CGRectGetHeight(bathroomGroup)) controlPoint1: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.14677 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.31087 * CGRectGetHeight(bathroomGroup)) controlPoint2: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.14516 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.37931 * CGRectGetHeight(bathroomGroup))];
            [tapPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.14516 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.55172 * CGRectGetHeight(bathroomGroup))];
            [tapPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.12903 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.55172 * CGRectGetHeight(bathroomGroup))];
            [tapPath closePath];
            [UIColor.whiteColor setFill];
            [tapPath fill];


            //// Bath Left Leg Drawing
            UIBezierPath* bathLeftLegPath = UIBezierPath.bezierPath;
            [bathLeftLegPath moveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.19355 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.89655 * CGRectGetHeight(bathroomGroup))];
            [bathLeftLegPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.16129 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.89655 * CGRectGetHeight(bathroomGroup))];
            [bathLeftLegPath addCurveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.12903 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 1.00000 * CGRectGetHeight(bathroomGroup)) controlPoint1: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.16129 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.89655 * CGRectGetHeight(bathroomGroup)) controlPoint2: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.15765 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.94600 * CGRectGetHeight(bathroomGroup))];
            [bathLeftLegPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.16129 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 1.00000 * CGRectGetHeight(bathroomGroup))];
            [bathLeftLegPath addCurveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.19355 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.89655 * CGRectGetHeight(bathroomGroup)) controlPoint1: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.18154 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.95385 * CGRectGetHeight(bathroomGroup)) controlPoint2: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.19355 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.89655 * CGRectGetHeight(bathroomGroup))];
            [bathLeftLegPath closePath];
            [UIColor.whiteColor setFill];
            [bathLeftLegPath fill];


            //// Bath Rim Drawing
            UIBezierPath* bathRimPath = UIBezierPath.bezierPath;
            [bathRimPath moveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.53830 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.62278 * CGRectGetHeight(bathroomGroup))];
            [bathRimPath addCurveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.53830 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.51515 * CGRectGetHeight(bathroomGroup)) controlPoint1: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.64852 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.59306 * CGRectGetHeight(bathroomGroup)) controlPoint2: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.64852 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.54487 * CGRectGetHeight(bathroomGroup))];
            [bathRimPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.13912 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.51515 * CGRectGetHeight(bathroomGroup))];
            [bathRimPath addCurveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.13912 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.62278 * CGRectGetHeight(bathroomGroup)) controlPoint1: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.02889 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.54487 * CGRectGetHeight(bathroomGroup)) controlPoint2: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.02889 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.59306 * CGRectGetHeight(bathroomGroup))];
            [bathRimPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.53830 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.62278 * CGRectGetHeight(bathroomGroup))];
            [bathRimPath closePath];
            CGContextSaveGState(context);
            CGContextSetShadowWithColor(context, bottomThinShadowOffset, bottomThinShadowBlurRadius, [bottomThinShadow CGColor]);
            [UIColor.whiteColor setFill];
            [bathRimPath fill];
            CGContextRestoreGState(context);



            //// Bath Inside Drawing
            UIBezierPath* bathInsidePath = UIBezierPath.bezierPath;
            [bathInsidePath moveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.52689 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.58830 * CGRectGetHeight(bathroomGroup))];
            [bathInsidePath addCurveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.52689 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.54963 * CGRectGetHeight(bathroomGroup)) controlPoint1: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.63082 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.57762 * CGRectGetHeight(bathroomGroup)) controlPoint2: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.63082 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.56031 * CGRectGetHeight(bathroomGroup))];
            [bathInsidePath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.15053 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.54963 * CGRectGetHeight(bathroomGroup))];
            [bathInsidePath addCurveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.15053 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.58830 * CGRectGetHeight(bathroomGroup)) controlPoint1: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.04660 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.56031 * CGRectGetHeight(bathroomGroup)) controlPoint2: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.04660 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.57762 * CGRectGetHeight(bathroomGroup))];
            [bathInsidePath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.52689 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.58830 * CGRectGetHeight(bathroomGroup))];
            [bathInsidePath closePath];
            [baseLightColor setFill];
            [bathInsidePath fill];
        }


        //// Towel and Rail Group
        {
            //// Towel Rail Drawing
            UIBezierPath* towelRailPath = UIBezierPath.bezierPath;
            [towelRailPath moveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.66129 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.34483 * CGRectGetHeight(bathroomGroup))];
            [towelRailPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.96774 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.34483 * CGRectGetHeight(bathroomGroup))];
            [towelRailPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.96774 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.31034 * CGRectGetHeight(bathroomGroup))];
            [towelRailPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.66129 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.31034 * CGRectGetHeight(bathroomGroup))];
            [towelRailPath addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.66129 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.34483 * CGRectGetHeight(bathroomGroup))];
            [towelRailPath closePath];
            CGContextSaveGState(context);
            CGContextSetShadowWithColor(context, bottomShadowOffset, bottomShadowBlurRadius, [bottomShadow CGColor]);
            [UIColor.whiteColor setFill];
            [towelRailPath fill];
            CGContextRestoreGState(context);



            //// Towel Group
            {
                CGContextSaveGState(context);
                CGContextSetShadowWithColor(context, bottomShadowOffset, bottomShadowBlurRadius, [bottomShadow CGColor]);
                CGContextBeginTransparencyLayer(context, NULL);


                //// Towel White Drawing
                UIBezierPath* towelWhitePath = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(bathroomGroup) + floor(CGRectGetWidth(bathroomGroup) * 0.70968 + 0.5), CGRectGetMinY(bathroomGroup) + floor(CGRectGetHeight(bathroomGroup) * 0.27586 + 0.5), floor(CGRectGetWidth(bathroomGroup) * 0.91935 + 0.5) - floor(CGRectGetWidth(bathroomGroup) * 0.70968 + 0.5), floor(CGRectGetHeight(bathroomGroup) * 0.82759 + 0.5) - floor(CGRectGetHeight(bathroomGroup) * 0.27586 + 0.5))];
                [UIColor.whiteColor setFill];
                [towelWhitePath fill];


                //// Towel Stripe 1 Drawing
                UIBezierPath* towelStripe1Path = UIBezierPath.bezierPath;
                [towelStripe1Path moveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.72581 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.27586 * CGRectGetHeight(bathroomGroup))];
                [towelStripe1Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.72581 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.82759 * CGRectGetHeight(bathroomGroup))];
                [towelStripe1Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.74194 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.82759 * CGRectGetHeight(bathroomGroup))];
                [towelStripe1Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.74194 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.27586 * CGRectGetHeight(bathroomGroup))];
                [towelStripe1Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.72581 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.27586 * CGRectGetHeight(bathroomGroup))];
                [towelStripe1Path closePath];
                [baseLightColor setFill];
                [towelStripe1Path fill];


                //// Towel Stripe 2 Drawing
                UIBezierPath* towelStripe2Path = UIBezierPath.bezierPath;
                [towelStripe2Path moveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.75806 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.27586 * CGRectGetHeight(bathroomGroup))];
                [towelStripe2Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.75806 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.82759 * CGRectGetHeight(bathroomGroup))];
                [towelStripe2Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.77419 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.82759 * CGRectGetHeight(bathroomGroup))];
                [towelStripe2Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.77419 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.27586 * CGRectGetHeight(bathroomGroup))];
                [towelStripe2Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.75806 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.27586 * CGRectGetHeight(bathroomGroup))];
                [towelStripe2Path closePath];
                [baseLightColor setFill];
                [towelStripe2Path fill];


                //// Towel Stripe 3 Drawing
                UIBezierPath* towelStripe3Path = UIBezierPath.bezierPath;
                [towelStripe3Path moveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.79032 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.27586 * CGRectGetHeight(bathroomGroup))];
                [towelStripe3Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.79032 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.82759 * CGRectGetHeight(bathroomGroup))];
                [towelStripe3Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.80645 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.82759 * CGRectGetHeight(bathroomGroup))];
                [towelStripe3Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.80645 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.27586 * CGRectGetHeight(bathroomGroup))];
                [towelStripe3Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.79032 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.27586 * CGRectGetHeight(bathroomGroup))];
                [towelStripe3Path closePath];
                [baseLightColor setFill];
                [towelStripe3Path fill];


                //// Towel Stripe 4 Drawing
                UIBezierPath* towelStripe4Path = UIBezierPath.bezierPath;
                [towelStripe4Path moveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.82258 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.27586 * CGRectGetHeight(bathroomGroup))];
                [towelStripe4Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.82258 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.82759 * CGRectGetHeight(bathroomGroup))];
                [towelStripe4Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.83871 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.82759 * CGRectGetHeight(bathroomGroup))];
                [towelStripe4Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.83871 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.27586 * CGRectGetHeight(bathroomGroup))];
                [towelStripe4Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.82258 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.27586 * CGRectGetHeight(bathroomGroup))];
                [towelStripe4Path closePath];
                [baseLightColor setFill];
                [towelStripe4Path fill];


                //// Towel Stripe 5 Drawing
                UIBezierPath* towelStripe5Path = UIBezierPath.bezierPath;
                [towelStripe5Path moveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.85484 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.27586 * CGRectGetHeight(bathroomGroup))];
                [towelStripe5Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.85484 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.82759 * CGRectGetHeight(bathroomGroup))];
                [towelStripe5Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.87097 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.82759 * CGRectGetHeight(bathroomGroup))];
                [towelStripe5Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.87097 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.27586 * CGRectGetHeight(bathroomGroup))];
                [towelStripe5Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.85484 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.27586 * CGRectGetHeight(bathroomGroup))];
                [towelStripe5Path closePath];
                [baseLightColor setFill];
                [towelStripe5Path fill];


                //// Towel Stripe 6 Drawing
                UIBezierPath* towelStripe6Path = UIBezierPath.bezierPath;
                [towelStripe6Path moveToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.88710 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.27586 * CGRectGetHeight(bathroomGroup))];
                [towelStripe6Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.88710 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.82759 * CGRectGetHeight(bathroomGroup))];
                [towelStripe6Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.90323 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.82759 * CGRectGetHeight(bathroomGroup))];
                [towelStripe6Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.90323 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.27586 * CGRectGetHeight(bathroomGroup))];
                [towelStripe6Path addLineToPoint: CGPointMake(CGRectGetMinX(bathroomGroup) + 0.88710 * CGRectGetWidth(bathroomGroup), CGRectGetMinY(bathroomGroup) + 0.27586 * CGRectGetHeight(bathroomGroup))];
                [towelStripe6Path closePath];
                [baseLightColor setFill];
                [towelStripe6Path fill];


                CGContextEndTransparencyLayer(context);
                CGContextRestoreGState(context);
            }
        }
    }
}

+ (void)drawFrontDoorWithFrame: (CGRect)frame
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* translucentBlack = [UIColor colorWithRed: 0 green: 0 blue: 0 alpha: 0.5];
    UIColor* baseColor = [UIColor colorWithRed: 0.808 green: 0.638 blue: 0.425 alpha: 1];
    CGFloat baseColorRGBA[4];
    [baseColor getRed: &baseColorRGBA[0] green: &baseColorRGBA[1] blue: &baseColorRGBA[2] alpha: &baseColorRGBA[3]];

    UIColor* baseLightColor = [UIColor colorWithRed: (baseColorRGBA[0] * 0.5 + 0.5) green: (baseColorRGBA[1] * 0.5 + 0.5) blue: (baseColorRGBA[2] * 0.5 + 0.5) alpha: (baseColorRGBA[3] * 0.5 + 0.5)];
    UIColor* translucentBaseColor = [UIColor colorWithRed: (baseColorRGBA[0] * 0.5 + 0.5) green: (baseColorRGBA[1] * 0.5 + 0.5) blue: (baseColorRGBA[2] * 0.5 + 0.5) alpha: (baseColorRGBA[3] * 0.5 + 0.5)];
    CGFloat translucentBaseColorRGBA[4];
    [translucentBaseColor getRed: &translucentBaseColorRGBA[0] green: &translucentBaseColorRGBA[1] blue: &translucentBaseColorRGBA[2] alpha: &translucentBaseColorRGBA[3]];

    UIColor* bevelShadowColor2 = [UIColor colorWithRed: (translucentBaseColorRGBA[0] * 0.15 + 0.85) green: (translucentBaseColorRGBA[1] * 0.15 + 0.85) blue: (translucentBaseColorRGBA[2] * 0.15 + 0.85) alpha: (translucentBaseColorRGBA[3] * 0.15 + 0.85)];
    UIColor* baseLighterColor = [UIColor colorWithRed: (baseColorRGBA[0] * 0.2 + 0.8) green: (baseColorRGBA[1] * 0.2 + 0.8) blue: (baseColorRGBA[2] * 0.2 + 0.8) alpha: (baseColorRGBA[3] * 0.2 + 0.8)];
    UIColor* blackOpacity15 = [UIColor colorWithRed: 0 green: 0 blue: 0 alpha: 0.15];

    //// Shadow Declarations
    UIColor* bottomThinShadow = translucentBlack;
    CGSize bottomThinShadowOffset = CGSizeMake(0.1, 1.1);
    CGFloat bottomThinShadowBlurRadius = 2;
    UIColor* bottomShadow = translucentBlack;
    CGSize bottomShadowOffset = CGSizeMake(0.1, 2.1);
    CGFloat bottomShadowBlurRadius = 3;
    UIColor* whiteBottom = UIColor.whiteColor;
    CGSize whiteBottomOffset = CGSizeMake(0.1, 2.1);
    CGFloat whiteBottomBlurRadius = 0;
    UIColor* bevelShadow2 = bevelShadowColor2;
    CGSize bevelShadow2Offset = CGSizeMake(0.1, -2.1);
    CGFloat bevelShadow2BlurRadius = 2;
    UIColor* darkInner = blackOpacity15;
    CGSize darkInnerOffset = CGSizeMake(0.1, 1.1);
    CGFloat darkInnerBlurRadius = 1;


    //// Subframes
    CGRect frontDoorGroup = CGRectMake(CGRectGetMinX(frame) + 2, CGRectGetMinY(frame) + 2, CGRectGetWidth(frame) - 4, CGRectGetHeight(frame) - 4);


    //// Front Door Frame Group
    {
        //// Front Door Group
        {
            CGContextSaveGState(context);
            CGContextSetShadowWithColor(context, bottomShadowOffset, bottomShadowBlurRadius, [bottomShadow CGColor]);
            CGContextBeginTransparencyLayer(context, NULL);


            //// Door Step Drawing
            UIBezierPath* doorStepPath = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(frontDoorGroup) + floor(CGRectGetWidth(frontDoorGroup) * 0.00000 + 0.5), CGRectGetMinY(frontDoorGroup) + floor(CGRectGetHeight(frontDoorGroup) * 0.95455 + 0.5), floor(CGRectGetWidth(frontDoorGroup) * 1.00000 + 0.5) - floor(CGRectGetWidth(frontDoorGroup) * 0.00000 + 0.5), floor(CGRectGetHeight(frontDoorGroup) * 1.00000 + 0.5) - floor(CGRectGetHeight(frontDoorGroup) * 0.95455 + 0.5))];
            [baseLighterColor setFill];
            [doorStepPath fill];


            //// Door Panel Drawing
            UIBezierPath* doorPanelPath = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(frontDoorGroup) + floor(CGRectGetWidth(frontDoorGroup) * 0.07143 + 0.5), CGRectGetMinY(frontDoorGroup) + floor(CGRectGetHeight(frontDoorGroup) * 0.00000 + 0.5), floor(CGRectGetWidth(frontDoorGroup) * 0.92857 + 0.5) - floor(CGRectGetWidth(frontDoorGroup) * 0.07143 + 0.5), floor(CGRectGetHeight(frontDoorGroup) * 0.95455 + 0.5) - floor(CGRectGetHeight(frontDoorGroup) * 0.00000 + 0.5))];
            [baseLighterColor setFill];
            [doorPanelPath fill];

            ////// Door Panel Inner Shadow
            CGContextSaveGState(context);
            UIRectClip(doorPanelPath.bounds);
            CGContextSetShadowWithColor(context, CGSizeZero, 0, NULL);

            CGContextSetAlpha(context, CGColorGetAlpha([bevelShadow2 CGColor]));
            CGContextBeginTransparencyLayer(context, NULL);
            {
                UIColor* opaqueShadow = [bevelShadow2 colorWithAlphaComponent: 1];
                CGContextSetShadowWithColor(context, bevelShadow2Offset, bevelShadow2BlurRadius, [opaqueShadow CGColor]);
                CGContextSetBlendMode(context, kCGBlendModeSourceOut);
                CGContextBeginTransparencyLayer(context, NULL);

                [opaqueShadow setFill];
                [doorPanelPath fill];

                CGContextEndTransparencyLayer(context);
            }
            CGContextEndTransparencyLayer(context);
            CGContextRestoreGState(context);



            //// Door Top Panel Drawing
            UIBezierPath* doorTopPanelPath = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(frontDoorGroup) + floor(CGRectGetWidth(frontDoorGroup) * 0.25000 + 0.5), CGRectGetMinY(frontDoorGroup) + floor(CGRectGetHeight(frontDoorGroup) * 0.09091 + 0.5), floor(CGRectGetWidth(frontDoorGroup) * 0.78571 + 0.5) - floor(CGRectGetWidth(frontDoorGroup) * 0.25000 + 0.5), floor(CGRectGetHeight(frontDoorGroup) * 0.45455 + 0.5) - floor(CGRectGetHeight(frontDoorGroup) * 0.09091 + 0.5))];
            CGContextSaveGState(context);
            CGContextSetShadowWithColor(context, whiteBottomOffset, whiteBottomBlurRadius, [whiteBottom CGColor]);
            [baseLightColor setFill];
            [doorTopPanelPath fill];

            ////// Door Top Panel Inner Shadow
            CGContextSaveGState(context);
            UIRectClip(doorTopPanelPath.bounds);
            CGContextSetShadowWithColor(context, CGSizeZero, 0, NULL);

            CGContextSetAlpha(context, CGColorGetAlpha([darkInner CGColor]));
            CGContextBeginTransparencyLayer(context, NULL);
            {
                UIColor* opaqueShadow = [darkInner colorWithAlphaComponent: 1];
                CGContextSetShadowWithColor(context, darkInnerOffset, darkInnerBlurRadius, [opaqueShadow CGColor]);
                CGContextSetBlendMode(context, kCGBlendModeSourceOut);
                CGContextBeginTransparencyLayer(context, NULL);

                [opaqueShadow setFill];
                [doorTopPanelPath fill];

                CGContextEndTransparencyLayer(context);
            }
            CGContextEndTransparencyLayer(context);
            CGContextRestoreGState(context);

            CGContextRestoreGState(context);



            //// Door Bottom Panel Drawing
            UIBezierPath* doorBottomPanelPath = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(frontDoorGroup) + floor(CGRectGetWidth(frontDoorGroup) * 0.25000 + 0.5), CGRectGetMinY(frontDoorGroup) + floor(CGRectGetHeight(frontDoorGroup) * 0.52273 + 0.5), floor(CGRectGetWidth(frontDoorGroup) * 0.78571 + 0.5) - floor(CGRectGetWidth(frontDoorGroup) * 0.25000 + 0.5), floor(CGRectGetHeight(frontDoorGroup) * 0.88636 + 0.5) - floor(CGRectGetHeight(frontDoorGroup) * 0.52273 + 0.5))];
            CGContextSaveGState(context);
            CGContextSetShadowWithColor(context, whiteBottomOffset, whiteBottomBlurRadius, [whiteBottom CGColor]);
            [baseLightColor setFill];
            [doorBottomPanelPath fill];

            ////// Door Bottom Panel Inner Shadow
            CGContextSaveGState(context);
            UIRectClip(doorBottomPanelPath.bounds);
            CGContextSetShadowWithColor(context, CGSizeZero, 0, NULL);

            CGContextSetAlpha(context, CGColorGetAlpha([darkInner CGColor]));
            CGContextBeginTransparencyLayer(context, NULL);
            {
                UIColor* opaqueShadow = [darkInner colorWithAlphaComponent: 1];
                CGContextSetShadowWithColor(context, darkInnerOffset, darkInnerBlurRadius, [opaqueShadow CGColor]);
                CGContextSetBlendMode(context, kCGBlendModeSourceOut);
                CGContextBeginTransparencyLayer(context, NULL);

                [opaqueShadow setFill];
                [doorBottomPanelPath fill];

                CGContextEndTransparencyLayer(context);
            }
            CGContextEndTransparencyLayer(context);
            CGContextRestoreGState(context);

            CGContextRestoreGState(context);



            //// Door Knob Drawing
            UIBezierPath* doorKnobPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(CGRectGetMinX(frontDoorGroup) + floor(CGRectGetWidth(frontDoorGroup) * 0.10714 + 0.5), CGRectGetMinY(frontDoorGroup) + floor(CGRectGetHeight(frontDoorGroup) * 0.45455 + 0.5), floor(CGRectGetWidth(frontDoorGroup) * 0.21429 + 0.5) - floor(CGRectGetWidth(frontDoorGroup) * 0.10714 + 0.5), floor(CGRectGetHeight(frontDoorGroup) * 0.52273 + 0.5) - floor(CGRectGetHeight(frontDoorGroup) * 0.45455 + 0.5))];
            CGContextSaveGState(context);
            CGContextSetShadowWithColor(context, bottomThinShadowOffset, bottomThinShadowBlurRadius, [bottomThinShadow CGColor]);
            [UIColor.whiteColor setFill];
            [doorKnobPath fill];

            ////// Door Knob Inner Shadow
            CGContextSaveGState(context);
            UIRectClip(doorKnobPath.bounds);
            CGContextSetShadowWithColor(context, CGSizeZero, 0, NULL);

            CGContextSetAlpha(context, CGColorGetAlpha([bevelShadow2 CGColor]));
            CGContextBeginTransparencyLayer(context, NULL);
            {
                UIColor* opaqueShadow = [bevelShadow2 colorWithAlphaComponent: 1];
                CGContextSetShadowWithColor(context, bevelShadow2Offset, bevelShadow2BlurRadius, [opaqueShadow CGColor]);
                CGContextSetBlendMode(context, kCGBlendModeSourceOut);
                CGContextBeginTransparencyLayer(context, NULL);

                [opaqueShadow setFill];
                [doorKnobPath fill];

                CGContextEndTransparencyLayer(context);
            }
            CGContextEndTransparencyLayer(context);
            CGContextRestoreGState(context);

            CGContextRestoreGState(context);



            CGContextEndTransparencyLayer(context);
            CGContextRestoreGState(context);
        }
    }
}

@end
