//
//  SampleStyleKit.h
//  BFWDrawView
//
//  Created by Tom Brodhurst-Hill on 2/05/2015.
//  Copyright (c) 2015 BareFeetWare. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface SampleStyleKit : NSObject

// Drawing Methods
+ (void)drawPacManWithFrame: (CGRect)frame animation: (CGFloat)animation;
+ (void)drawBathroomWithFrame: (CGRect)frame;
+ (void)drawFrontDoor;

@end
